workspace:
  base: /srv/drone-demo
  path: .
  
pipeline:
  deploy-test:
    image: appleboy/drone-ssh
    secrets: [ test_host, test_username, test_password ]
    host: $TEST_HOST
    username: $TEST_USERNAME
    password: $TEST_PASSWORD
    port: 22
    script:
      - echo ${TEST_HOST}
      - echo ${TEST_USERNAME}
      - echo ${TEST_PASSWORD}
      - ping www.baidu.com
#     environment:
#       TEST_HOST:
#         from_secret: test_host
#       TEST_HOST_USERNAME:
#         from_secret: test_host_username
#       TEST_HOST_PASSWORD:
#         from_secret: test_host_password
#   publish:
#     image: plugins/docker
#     registry: registry.cn-hangzhou.aliyuncs.com
#     repo: registry.cn-hangzhou.aliyuncs.com/tryto/baota
#     tags:
#       - ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:8}
#     secrets: [ docker_username, docker_password ]
#     insecure: true
#   deploy-test:
#       image: appleboy/drone-ssh
#       host: [ test_host ]
#       username: [ test_host_username ]
#       password: [ test_host_password ]
#       command_timeout: 2m
#       port: 22
#       script:
#         - sudo docker pull registry.cn-hangzhou.aliyuncs.com/tryto/baota:${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:8}
#         - docker rm -f docker-demo || true
#         - docker run -d -p 18888:80 --name docker-demo registry.cn-hangzhou.aliyuncs.com/tryto/baota:${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:8}
         
