workspace:
  base: /srv/drone-demo
  path: .
  
pipeline:
  publish:
    image: plugins/docker
    registry: registry.cn-hangzhou.aliyuncs.com
    repo: registry.cn-hangzhou.aliyuncs.com/tryto/baota
    tags:
      - ${DRONE_COMMIT_SHA}
    secrets: [ docker_username, docker_password ]
    insecure: true
