kind: pipeline
name: demo

steps:
- name: publish
  image: plugins/docker
  settings:
    registry: registry.cn-hangzhou.aliyuncs.com
    repo: registry.cn-hangzhou.aliyuncs.com/tryto/baota
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - baota-${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:8}
    insecure: true

- name: run-test
  image: appleboy/drone-ssh
  pull: true
  settings:
    command_timeout: 2m
    port: 22
    host:
      from_secret: test_host
    username:
      from_secret: test_username
    password:
      from_secret: test_password
    script:
      - echo "登录..."
      - echo "删除旧容器和镜像"
      - docker rmi $(docker images | grep "baota-${DRONE_COMMIT_BRANCH}*" | awk "{print $3}")
      - docker rm -f $(docker ps -a |  grep "baota-${DRONE_COMMIT_BRANCH}*"  | awk '{print $1}')
      - sudo docker pull registry.cn-hangzhou.aliyuncs.com/tryto/baota:baota-${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:8}
      - echo "镜像运行"
      - docker run -d -p 18888:80 --name baota-${DRONE_COMMIT_BRANCH} registry.cn-hangzhou.aliyuncs.com/tryto/baota:baota-${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:8}
