workspace:
  base: /srv/drone-demo
  path: .
  
pipeline:
  publish:
    image: plugins/docker
    registry: registry.cn-hangzhou.aliyuncs.com
    repo: registry.cn-hangzhou.aliyuncs.com/tryto/baota
    tags:
      - ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:8}
    secrets: [ docker_username, docker_password ]
    insecure: true
  deploy-test:
      image: appleboy/drone-ssh
      host:
        - 49.235.140.211
      username: [ test_host_username ]
      password: [ test_host_password ]
      port: 22
      script:
        - sudo docker pull registry.cn-hangzhou.aliyuncs.com/tryto/baota:${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:8}
        - docker rm -f docker-demo || true
        - docker run -d -p 18888:80 --name docker-demo registry.cn-hangzhou.aliyuncs.com/tryto/baota:${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:8}
         
